### ISSUE TITLE
Jetpack failed with OSP16 os-net-config for supermicro hosts [5039ms]

### ISSUE THREAD

**Issue by pradiptapks** [redhat-performance/jetpack#160]
Using the latest OSP16 puddle (passed_phased2), the overcloud deployment failed while performing networking configuration on the controller and compute node.

Although there is no change in interface template for supermicro server, but the deployment failed with the below exception:

```
[root@controller-0 ~]# os-net-config --config-file /etc/os-net-config/config.json --noop
Traceback (most recent call last):
  File "/bin/os-net-config", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/os_net_config/cli.py", line 290, in main
    obj = objects.object_from_json(iface_json)
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 51, in object_from_json
    return OvsBridge.from_json(json)
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 675, in from_json
    members = _update_members(json, nic_mapping, persist_mapping)
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 126, in _update_members
    members.append(object_from_json(member))
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 47, in object_from_json
    return Interface.from_json(json)
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 489, in from_json
    hotplug=hotplug, linkdelay=linkdelay)
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 476, in __init__
    nm_controlled, onboot, domain)
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 335, in __init__
    mapped_nic_names = mapped_nics(nic_mapping)
  File "/usr/lib/python3.6/site-packages/os_net_config/objects.py", line 183, in mapped_nics
    raise InvalidConfigException(msg)
os_net_config.objects.InvalidConfigException: cannot map enp1s0f1 to alias enp1s0f1, alias overlaps with active NIC.
```

So far the controller and compute nodes are failed.  
Sample trace failure details for overcloud controller: http://paste.openstack.org/show/pXMPJPFU1yKw6X8OoW4E/

**Comment by pradiptapks** [comment]
To isolate the issue, currently validating the Jetpack with OSP13 latest puddle.

**Comment by pradiptapks** [comment]
Deployment succeeded with OSP13, no above os-net-config issue reported.

As this issue didn't appear in other scale lab servers, so redeploying the environment with OSP16 and the following puddle: 

> RHOS_TRUNK-16.0-RHEL-8-20200226.n.1

**Comment by pradiptapks** [comment]
I am closing this bug as the reported issue didn't appear after multiple attempts in SM 5039ms
