### ISSUE TITLE
Add retries ( -r option) for badfish commands

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#17]
Need to check if we need to add -r option (badifsh has this option for retries) to badfish command.
I tried manually running the badfish command, which was successful only on 3rd attempt ( though I didn't try anything in between). We need to discuss if this is needed or not.

[root@hypervisor-0 badfish]# ./badfish.py -H mgmt-f03-h01-000-r620.rdu2.scalelab.redhat.com -u quads -p 496724 -i config/idrac_interfaces.yml --boot-to-type foreman --pxe
- ERROR    - Failed to communicate with server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:877)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mgmt-f03-h01-000-r620.rdu2.scalelab.redhat.com', port=443): Max retries exceeded with url: /redfish/v1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./badfish.py", line 64, in get_request
    _response = requests.get(uri, auth=(self.username, self.password), verify=False, timeout=60)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mgmt-f03-h01-000-r620.rdu2.scalelab.redhat.com', port=443): Max retries exceeded with url: /redfish/v1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),))
[root@hypervisor-0 badfish]# ./badfish.py -H mgmt-f03-h01-000-r620.rdu2.scalelab.redhat.com -u quads -p 496724 -i config/idrac_interfaces.yml --boot-to-type foreman --pxe
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- WARNING  - iDRAC version installed does not support DellJobService
- WARNING  - Clearing job queue for job IDs: ['JID_686759556041'].
- INFO     - Job queue for iDRAC mgmt-f03-h01-000-r620.rdu2.scalelab.redhat.com successfully cleared.
- INFO     - Command passed to set BIOS attribute pending values.
- INFO     - POST command passed to create target config job.
- INFO     - JID_689060662084 job ID successfully created.
- INFO     - Command passed to check job status, code 200 returned.
- INFO     - Job id JID_689060662084 successfully scheduled.
- INFO     - PATCH command passed to set next boot onetime boot device to: "Pxe".

**Comment by venkataanil** [comment]
Latest commit fixed that.
