### ISSUE TITLE
pip install failing 

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#197]
TASK [infrared setup] *******************************************************************************************************************************************************
task path: /root/jetpack/tasks/setup_infrared.yml:13                                                                                                                         
ok: [localhost] => {"changed": false, "cmd": "virtualenv .venv && source .venv/bin/activate\npip install --upgrade pip\npip install --upgrade setuptools\npip install .\nrm -
rf /root/.infrared\n", "delta": "0:00:12.087199", "end": "2020-05-18 13:33:23.934863", "rc": 0, "start": "2020-05-18 13:33:11.847664", "stderr": "    ERROR: Command errored 
out with exit status 1:\n     command: /root/infrared/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/root/infrared/setup.py'\"'\"'; __file__='
\"'\"'/root/infrared/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(co
mpile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dut3727_\n         cwd: /root/infrared/\n    Complete output (20 lines):\n    running e
gg_info\n    creating /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info\n    writing pbr to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/pbr.json\n    writing /tmp/pip-pi
p-egg-info-dut3727_/infrared.egg-info/PKG-INFO\n    writing dependency_links to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/dependency_links.txt\n    writing entry poin
ts to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/entry_points.txt\n    writing requirements to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/requires.txt\n    writi
ng top-level names to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/top_level.txt\n    [pbr] Processing SOURCES.txt\n    writing manifest file '/tmp/pip-pip-egg-info-dut3
727_/infrared.egg-info/SOURCES.txt'\n    [pbr] In git context, generating filelist from git\n    warning: no files found matching 'AUTHORS'\n    warning: no files found matc
hing 'ChangeLog'\n    warning: no previously-included files matching '*.pyc' found anywhere in distribution\n    writing manifest file '/tmp/pip-pip-egg-info-dut3727_/infrar
ed.egg-info/SOURCES.txt'\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/root/infrared/setup.py\", line 8, in <module>\n
        if 'redhat' in platform.linux_distribution(\n    AttributeError: module 'platform' has no attribute 'linux_distribution'\n    ---------------------------------------
-\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.", "stderr_lines": ["    ERROR: Command errored out with ex
it status 1:", "     command: /root/infrared/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/root/infrared/setup.py'\"'\"'; __file__='\"'\"'/ro
ot/infrared/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(cod
e, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dut3727_", "         cwd: /root/infrared/", "    Complete output (20 lines):", "    running egg_
info", "    creating /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info", "    writing pbr to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/pbr.json", "    writing /tmp/pip
-pip-egg-info-dut3727_/infrared.egg-info/PKG-INFO", "    writing dependency_links to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/dependency_links.txt", "    writing ent
ry points to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/entry_points.txt", "    writing requirements to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/requires.txt",
 "    writing top-level names to /tmp/pip-pip-egg-info-dut3727_/infrared.egg-info/top_level.txt", "    [pbr] Processing SOURCES.txt", "    writing manifest file '/tmp/pip-pi
p-egg-info-dut3727_/infrared.egg-info/SOURCES.txt'", "    [pbr] In git context, generating filelist from git", "    warning: no files found matching 'AUTHORS'", "    warning
: no files found matching 'ChangeLog'", "    warning: no previously-included files matching '*.pyc' found anywhere in distribution", "    writing manifest file '/tmp/pip-pip
-egg-info-dut3727_/infrared.egg-info/SOURCES.txt'", "    Traceback (most recent call last):", "      File \"<string>\", line 1, in <module>", "      File \"/root/infrared/se
tup.py\", line 8, in <module>", "        if 'redhat' in platform.linux_distribution(", "    AttributeError: module 'platform' has no attribute 'linux_distribution'", "    --
--------------------------------------", "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output."], "stdout": "Using
 base prefix '/usr'\nNew python executable in /root/infrared/.venv/bin/python3\nAlso creating executable in /root/infrared/.venv/bin/python\nInstalling setuptools, pip, wheel...\ndone.\nRequirement already up-to-date: pip in ./.venv/lib/python3.8/site-packages (20.1)\nRequirement already up-to-date: setuptools in ./.venv/lib/python3.8/site-packages (46.4.0)\nProcessing /root/infrared", "stdout_lines": ["Using base prefix '/usr'", "New python executable in /root/infrared/.venv/bin/python3", "Also creating executable in /root/infrared/.venv/bin/python", "Installing setuptools, pip, wheel...", "done.", "Requirement already up-to-date: pip in ./.venv/lib/python3.8/site-packages (20.1)", "Requirement already up-to-date: setuptools in ./.venv/lib/python3.8/site-packages (46.4.0)", "Processing /root/infrared"]}

I tried manually the steps and got below errors
[root@badfish-public jetpack]# cd /root/infrared
[root@badfish-public infrared]# virtualenv .venv
Using base prefix '/usr'
New python executable in /root/infrared/.venv/bin/python3
Not overwriting existing python script /root/infrared/.venv/bin/python (you must use /root/infrared/.venv/bin/python3)
Installing setuptools, pip, wheel...
done.
[root@badfish-public infrared]# source .venv/bin/activate
(.venv) [root@badfish-public infrared]# pip install --upgrade pip
Requirement already up-to-date: pip in ./.venv/lib/python3.8/site-packages (20.1)
(.venv) [root@badfish-public infrared]# pip install --upgrade setuptools
Requirement already up-to-date: setuptools in ./.venv/lib/python3.8/site-packages (46.4.0)
(.venv) [root@badfish-public infrared]# pip install .
Processing /root/infrared
    ERROR: Command errored out with exit status 1:
     command: /root/infrared/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/infrared/setup.py'"'"'; __file__='"'"'/root/infrared/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uzuz18ed
         cwd: /root/infrared/
    Complete output (20 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info
    writing pbr to /tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/pbr.json
    writing /tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/entry_points.txt
    writing requirements to /tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/top_level.txt
    [pbr] Processing SOURCES.txt
    writing manifest file '/tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/SOURCES.txt'
    [pbr] In git context, generating filelist from git
    warning: no files found matching 'AUTHORS'
    warning: no files found matching 'ChangeLog'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file '/tmp/pip-pip-egg-info-uzuz18ed/infrared.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/infrared/setup.py", line 8, in <module>
        if 'redhat' in platform.linux_distribution(
    AttributeError: module 'platform' has no attribute 'linux_distribution'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(.venv) [root@badfish-public infrared]#

**Comment by venkataanil** [comment]
I am running jetpack on fedora32 (python 3.8) and see that error.
Looks like python3.8 has this issue https://github.com/pymssql/pymssql/issues/586

Infrared can't be run from fedora32
